### ISSUE TITLE
Rewrite your compiler in Rust

### ISSUE THREAD

**Issue by thesilican** [TheOneKevin/cs444-compiler#1]
Rust is a modern and quite frankly superior language over C++ in every aspect. Writing your project in C++ when Rust is available is a massive red flag, quite frankly if I was your project manager I would have had you all fired and burned all laptops and servers containing your code, as well as reported you to the FBI for the federal crime of using a memory-unsafe language. You should all feel ashamed and reminisce over the poor life choices that have lead you to this point.

**Comment by TheOneKevin** [comment]
Noted. Feel free to make a PR.
